---
  - name: Install apache on CentOS and Centos
    hosts: webserver
    become: yes
    tasks:
      - name: Install apache2 server
        package: 
          name: java-1.7.0-openjdk-devel
          state: present
        when: ansible_facts['distribution'] == "CentOS"
      - name: Add group
        group:
          name: tomcat
          state: present
      - name: Add user
        user: 
          name: tomcat
          home: /opt/tomcat
          group: tomcat
          shell: /bin.bash
          state: present
          password: $6$fP.2G.zIu7MbT8W$6IQ1Rgsd88Fovpd5hsaRk.6wd65r9wcMvFrQKwQgzNopdEQJpywZaIwJogyPsZHANnvSSiF80p/GL8L.GRE8B/
        when: ansible_facts['distribution'] == "CentOS"
      - name: download tomcat
        get_url:
          url: "https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.zip"
          dest: "/tmp/apache-tomcat-8.5.61.zip"
        when: ansible_facts['distribution'] == "CentOS"
      - name: Install Unzip
        package: 
          name: unzip
          state: present
        when: ansible_facts['distribution'] == "CentOS"
      - name: extract tomcat
        unarchive:
          src: "/tmp/apache-tomcat-8.5.61.zip"
          dest: "/opt/tomcat"
          remote_src: yes
        when: ansible_facts['distribution'] == "CentOS"

