---
  - name: Install apache on Ubuntu and Centos
    hosts: webserver
    become: yes
    vars: 
      tomcat_download_result:
    vars_files: 
      - var/tomcat_ubuntu_var.yaml
    tasks:
      - name: Install jdk server
        package:
          name: "{{ jdk_package_name }}"
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: Add group
        group:
          name: "{{ user_name }}"
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: Add user
        user:
          name: "{{ user_name }}"
          home: /opt/tomcat
          shell: /bin/bash
          state: present
          group: "{{ user_name }}"
          password: $6$fP.2G.zIu7MbT8W$6IQ1Rgsd88Fovpd5hsaRk.6wd65r9wcMvFrQKwQgzNopdEQJpywZaIwJogyPsZHANnvSSiF80p/GL8L.GRE8B/
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: download tomcat
        get_url:
          url: "{{ tomcat_download_uri }}"
          dest: "{{ tomcat_download_path }}"
          mode: "0440"
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: check stats on download file
        stat:
           path: "{{ tomcat_install_path }}"
        register: tomcat_download_result
      - name: Debug   
        debug:
           msg: "{{ tomcat_download_result.stat.exists }}"
      - name: install Unzip
        package:
          name: unzip
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: extract tomcat
        unarchive:
          remote_src: yes
          src: "{{ tomcat_download_path }}"
          dest: "/opt/tomcat"
          mode: 0644
        when: ansible_facts['distribution'] == "Ubuntu" and not tomcat_download_result.stat.exists
      - name: Create a symbolic link
        file: 
          src: /opt/tomcat/apache-tomcat-8.5.61
          dest: /opt/tomcat/latest
          state: link
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: Copy tomcat.service file
        copy:
          src: ~/Ansible/tomcat.service
          dest: /etc/systemd/system/tomcat.service
          mode: 0644
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: file permissions
        command: sudo chown -R tomcat:/opt/tomcat
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: file permissions
        command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: System deamon relaod
        systemd:
          daemon_reload: yes
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: System deamon relaod
        systemd:
          name: tomcat
          state: started
        when: ansible_facts['distribution'] == "Ubuntu"
          
