---
  - name: Install apache on Ubuntu and Centos
    hosts: webserver
    become: yes
    vars:
      tomcat_download_result:
    vars_files:
      - var/tomcat_ubuntu_var.yaml
    tasks:
      - name: Install jdk server
        package:
          name: "{{ jdk_package_name }}"
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: Add group
        group:
          name: "{{ user_name }}"
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: Add user
        user:
          name: "{{ user_name }}"
          home: "{{ tomcat_install_path }}"
          shell: /bin/false
          state: present
          group: "{{ user_name }}"
          password: $6$fP.2G.zIu7MbT8W$6IQ1Rgsd88Fovpd5hsaRk.6wd65r9wcMvFrQKwQgzNopdEQJpywZaIwJogyPsZHANnvSSiF80p/GL8L.GRE8B/
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: download tomcat
        get_url:
          url: "{{ tomcat_download_uri }}"
          dest: "{{ tomcat_download_path }}"
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: check stats on download file
        stat:
           path: "{{ tomcat_install_path }}/apache-tomcat-8.5.61/"
        register: tomcat_download_result
      - name: Debug
        debug:
           msg: "{{ tomcat_install_path}} {{ tomcat_download_result.stat.exists }}"
      - name: install Unzip
        package:
          name: unzip
          state: present
        when: ansible_facts['distribution'] == "Ubuntu"
      - name: extract tomcat
        unarchive:
          remote_src: yes
          src: "{{ tomcat_download_path }}"
          dest: "{{ tomcat_install_path }}"
        when: ansible_facts['distribution'] == "Ubuntu" and not tomcat_download_result.stat.exists
        notify:
         - Create a symbolic link
         - file permissions
         - file permissions for all sh files
      - name: Copy tomcat.service file
        copy:
          src: ~/Ansible/tomcat.service
          dest: /etc/systemd/system/tomcat.service
        when: ansible_facts['distribution'] == "Ubuntu"
        notify:
         - System deamon reload and tomcat start
    handlers:
      - name: Create a symbolic link
        file:
          src: /opt/tomcat/apache-tomcat-8.5.61
          dest: /opt/tomcat/latest
          owner:
          state: link
      - name: file permissions
        file:
           path: "{{ tomcat_install_path}}"
           recurse: yes
           owner: "{{ user_name }}"
           group: "{{ user_name }}"
           state: directory
      - name: file permissions for all sh files
        file:
           path: "{{ item }}"
           owner: "{{ user_name }}"
           group: "{{ user_name }}"
           mode : +x
        loop:
           - /opt/tomcat/latest/bin/catalina.sh
           - /opt/tomcat/latest/bin/ciphers.sh
           - /opt/tomcat/latest/bin/configtest.sh
           - /opt/tomcat/latest/bin/daemon.sh
           - /opt/tomcat/latest/bin/digest.sh
           - /opt/tomcat/latest/bin/setclasspath.sh
           - /opt/tomcat/latest/bin/shutdown.sh
           - /opt/tomcat/latest/bin/startup.sh
           - /opt/tomcat/latest/bin/tool-wrapper.sh
           - /opt/tomcat/latest/bin/version.sh
 
      - name: System deamon reload and tomcat start
        systemd:
          name: tomcat
          enabled: yes
          daemon_reload: yes
          state: started


                                                
