---
  - name: Install lampserver using variable on webserver
    hosts: webserver
    become: yes
    tasks: 
      - name: Install lampserver
        package:
            name: "{{ package_name }}"
            state: present
